---
functional:
  - Пользователь должен иметь возможность искать товары по ключевому слову или
    категории.
  - Пользователь должен иметь возможность фильтровать товары по цене, цвету,
    размеру и т.д.
  - Пользователь должен иметь возможность просматривать товары и просматривать
    подробную информацию о товаре.
  - Пользователь должен иметь возможность добавлять товары в корзину и
    просматривать содержимое корзины.
  - Сайт должен быть доступен на различных устройствах.
  - На странице корзины пользователь может удалить товар из корзины,продолжить
    выбирать товары в каталоге, оформить заказ с переходом на страницу оплаты.
  - Корзина хранится в сессии браузера.
non-functional:
  - Веб-сайт должен быть разработан с учетом удобства использования и
    оптимизирован для скорости работы.
  - Сайт должен быть безопасным и защищать данные пользователя.
  - Сайт должен быть способен обрабатывать большое количество трафика.
  - Сайт должен иметь мобильную версию.
  - Сайт должен быть протестирован на совместимость с последними версиями
    браузеров.
implicit:
  - При смене языка на русский все меню должно переводиться на русский язык.
  - Цена товара в долларах должна также показывать цену в рублях.
  - Должна быть возможность сортировки производителей в алфавитном порядке.

